- .gitignore
- .scripts/build_steps.sh
- .scripts/run_docker_build.sh
- recipe/activate.sh
- recipe/deactivate.sh
- recipe/install-files-core.sh
- recipe/meta.yaml
> Use activation scripts to get $MCSTAS set

- recipe/meta.yaml
Checklist
* [] Reset the build number to `0` (if the version changed)
Minor update due to upstream bug fix
> Updated SHA and build number due to minor bugfix

- recipe/meta.yaml
> Update conda builds with various McCode repo platform-independence work

- recipe/meta.yaml
Checklist
Trigger another rebuild
> Upstream changes in McCode repo -> trigger rebuild of new release

- recipe/meta.yaml
Checklist
Simply to initiate sync.
> Spawn update

- recipe/meta.yaml
Checklist
Updates / suggestions given via the similar mcxtrace-feedstock (1st step of making them as similar as possible).
> Updates / suggestions via sister-feedstock for McXtrace

- recipe/install-files-core.bat
- recipe/install-files-core.sh
- recipe/meta.yaml
Checklist
minor upstream changes - sync
> Upstream changes, remove acc_bind wrapper hack

- .ci_support/linux_64_.yaml
- .ci_support/osx_64_.yaml
- .ci_support/osx_arm64_.yaml
- .ci_support/win_64_.yaml
- recipe/meta.yaml
Checklist
Add nexus (from https://github.com/conda-forge/nexus-feedstock) as dependency for all platforms, bump build no.
> Enable NeXus as runtime dependency

- recipe/meta.yaml
(seems there was a clash between earlier PR and autobot work)
Checklist
> Attempt rebuild with increment of build no

- .ci_support/linux_64_.yaml
- recipe/meta.yaml
> Bump version no to pick up fix for failing Windows build

- recipe/install-files-core.bat
- recipe/meta.yaml
> Rebuild with updated windows MPI flags

- recipe/meta.yaml
> Bump due to upstream changes / impatience :-)

- recipe/meta.yaml
> Bump version no

- recipe/meta.yaml
> Add gsl dependency, bump version no

- recipe/meta.yaml
> Scoop up upstream updates

- recipe/meta.yaml
> Move to new, common version-tag for McStas and McXtrace

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_nodejs18.yaml
- .ci_support/linux_64_nodejs20.yaml
- .ci_support/osx_64_nodejs18.yaml
- .ci_support/osx_64_nodejs20.yaml
- .ci_support/osx_arm64_nodejs18.yaml
- .ci_support/osx_arm64_nodejs20.yaml
- .ci_support/win_64_nodejs18.yaml
- .ci_support/win_64_nodejs20.yaml
- README.md
- recipe/meta.yaml
> Prepare for incoming node.js dependency

- recipe/meta.yaml
> Attempt to trigger 3.4.51 build via PR

- recipe/meta.yaml
> Spawn update release

- recipe/meta.yaml
> Bump for 3.5.54

- recipe/meta.yaml
> Spawn conda rebuild

- recipe/meta.yaml
- recipe/release_sync.sh
> Update release 3.4.61

- recipe/meta.yaml
> Update release 3.4.62

- recipe/meta.yaml
> Spawn 3.4.64

- recipe/meta.yaml
> Move high-level dependencies away from low-level mcstas-core package

- recipe/meta.yaml
> Bump for 3.4.68

- recipe/meta.yaml
> Trigger a rebuild

- .ci_support/linux_aarch64_nodejs18.yaml
- .ci_support/linux_aarch64_nodejs20.yaml
- .travis.yml
- README.md
- conda-forge.yml
- recipe/meta.yaml
> Attempt including linux on aarch64

- recipe/meta.yaml
> Add rsync as conda dependency

- .azure-pipelines/azure-pipelines-osx.yml
- azure-pipelines.yml
- recipe/meta.yaml
- recipe/test_pkg.py
> New release and use copytree for examples

- .scripts/build_steps.sh
- .scripts/run_osx_build.sh
- .scripts/run_win_build.bat
- recipe/meta.yaml
> Bump release no. to take into account upstream changes

- .azure-pipelines/azure-pipelines-linux.yml
- .azure-pipelines/azure-pipelines-osx.yml
- .azure-pipelines/azure-pipelines-win.yml
- .ci_support/linux_64_nodejs20.yaml
- .ci_support/linux_64_nodejs22.yaml
- .ci_support/linux_aarch64_nodejs20.yaml
- .ci_support/linux_aarch64_nodejs22.yaml
- .ci_support/osx_64_nodejs22.yaml
- .ci_support/osx_arm64_nodejs22.yaml
- .ci_support/win_64_nodejs22.yaml
- .travis.yml
- README.md
- recipe/meta.yaml
> Add cif2hkl as runtime dep

- recipe/meta.yaml
> Add qtpy middelware and bump release

- recipe/meta.yaml
> Configure recipe for NCrystal 4.0.0

- .azure-pipelines/azure-pipelines-linux.yml
- .travis.yml
- README.md
- conda-forge.yml
- recipe/meta.yaml
> Experiment with travis build

- README.md
- recipe/meta.yaml
> Update org name and bump build no

- .gitignore
- .scripts/run_docker_build.sh
- README.md
- build-locally.py
- recipe/meta.yaml
> Correct recipe to pick up 3.5.25

- recipe/meta.yaml
> Trigger 3.5.26 with MCPL 2.0.0 support on all platforms
